/**
 * Generated by `ztron codegen`. Do not edit by hand.
 * Run `ztron codegen` after adding/changing commands.
 */
import { invoke as rawInvoke } from "@zturnlibs/ztron-api";
import type { InvokeOptions } from "@zturnlibs/ztron-api";

export type KnownCommands = {
    "d2r:getConfig": { args: Record<string, never>; result: { config: { version: number; gameDir: string | null; sources: { id: string; path: string; label: string; addedAt: number }[]; knownMods: { key: string; name: string; displayName: string | null; savepath: string; sourceId: string; sourcePath: string; relPath: string; variant: string; parseWarning: string | null; readmePath: string | null; }[]; profiles: { id: string; name: string; modName: string; extraArgs: string[]; note: string; createdAt: number }[]; installed: Record<string, { mode: string; installedAt: number; sourcePath: string }>; autoBackup: boolean; backupKeep: number; }; validation: { exists: boolean; hasD2R: boolean; hasModsDir: boolean } | null; } }
    "d2r:setGameDir": { args: { gameDir: string }; result: { ok: boolean; validation: { exists: boolean; hasD2R: boolean; hasModsDir: boolean } } }
    "d2r:pickFolder": { args: { title?: string }; result: { path: string | null } }
    "d2r:addSource": { args: { path: string; label?: string }; result: { source: { id: string; path: string; label: string; addedAt: number }; } }
    "d2r:removeSource": { args: { id: string }; result: { ok: boolean } }
    "d2r:scanSource": { args: { id: string }; result: { mods: { key: string; name: string; displayName: string | null; savepath: string; sourceId: string; sourcePath: string; relPath: string; variant: string; parseWarning: string | null; readmePath: string | null; }[]; warnings: string[]; scannedDirs: number; } }
    "d2r:listMods": { args: Record<string, never>; result: { mods: { key: string; name: string; displayName: string | null; savepath: string; sourceId: string; sourcePath: string; relPath: string; variant: string; parseWarning: string | null; readmePath: string | null; }[]; installed: Record<string, boolean>; suggestedArgs: Record<string, string[]>; } }
    "d2r:installMod": { args: { key: string; mode: string; overwrite: boolean; ch: string }; result: { ok: boolean; files: number; bytes: number; mode: string; errors: string[] } }
    "d2r:uninstallPreflight": { args: { name: string }; result: { installed: boolean; savepath: string | null; usesRootSaves: boolean; saveDir: string | null; saveDirExists: boolean; } }
    "d2r:uninstallMod": { args: { name: string }; result: { ok: boolean } }
    "d2r:readTextB64": { args: { path: string }; result: { b64: string | null; size: number } }
    "d2r:saveProfiles": { args: { profiles: { id: string; name: string; modName: string; extraArgs: string[]; note: string; createdAt: number }[]; }; result: { profiles: { id: string; name: string; modName: string; extraArgs: string[]; note: string; createdAt: number }[]; } }
    "d2r:launch": { args: { modName: string; extraArgs: string[] }; result: { pid: number; args: string[] } }
    "d2r:exportShortcut": { args: { name: string; modName: string; extraArgs: string[] }; result: { lnkPath: string } }
    "d2r:openDir": { args: { path: string }; result: { ok: boolean } }
    "d2r:saveOverview": { args: Record<string, never>; result: { root: { name: string; slot: string; path: string; exists: boolean; files: { name: string; size: number; mtime: number }[]; dirs: { name: string; files: number; bytes: number }[]; totalBytes: number; }; mods: { name: string; slot: string; path: string; exists: boolean; files: { name: string; size: number; mtime: number }[]; dirs: { name: string; files: number; bytes: number }[]; totalBytes: number; }[]; } }
    "d2r:listBackups": { args: Record<string, never>; result: { dir: string; backups: { id: string; createdAt: number; note: string; trigger: string; scopes: { slot: string; sourcePath: string }[]; files: number; bytes: number; signature: string; }[]; } }
    "d2r:backupNow": { args: { slots: string[]; note?: string }; result: { backup: { id: string; createdAt: number; note: string; trigger: string; scopes: { slot: string; sourcePath: string }[]; files: number; bytes: number; signature: string; }; } }
    "d2r:restoreBackup": { args: { id: string }; result: { ok: boolean; preRestoreId: string | null } }
    "d2r:deleteBackup": { args: { id: string }; result: { ok: boolean } }
    "d2r:setBackupNote": { args: { id: string; note: string }; result: { ok: boolean } }
    "d2r:setSavePrefs": { args: { autoBackup?: boolean; backupKeep?: number }; result: { ok: boolean; autoBackup: boolean; backupKeep: number } }
    "d2r:checkGameRunning": { args: Record<string, never>; result: { running: boolean } }
    "d2r:stashPickFile": { args: { title?: string }; result: { path: string | null } }
    "d2r:stashPreflight": { args: { slot: string }; result: { slot: string; fileName: string; path: string; exists: boolean; size: number; mtime: number; gameRunning: boolean; } }
    "d2r:stashReplace": { args: { slot: string; sourcePath: string; note?: string }; result: { ok: boolean; backupId: string | null; replaced: boolean } }
};

/** Type-safe invoke: cmd must be a known command, args/result inferred from its declaration. */
export function invoke<C extends keyof KnownCommands>(
  cmd: C,
  args: KnownCommands[C]["args"],
  options?: InvokeOptions,
): Promise<KnownCommands[C]["result"]>;

export async function invoke(
  cmd: string,
  args?: unknown,
  options?: InvokeOptions,
): Promise<unknown> {
  if (cmd === "d2r:getConfig") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:setGameDir") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:pickFolder") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:addSource") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:removeSource") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:scanSource") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:listMods") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:installMod") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:uninstallPreflight") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:uninstallMod") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:readTextB64") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:saveProfiles") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:launch") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:exportShortcut") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:openDir") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:saveOverview") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:listBackups") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:backupNow") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:restoreBackup") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:deleteBackup") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:setBackupNote") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:setSavePrefs") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:checkGameRunning") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:stashPickFile") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:stashPreflight") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:stashReplace") return rawInvoke(cmd, args as never, options);
  return rawInvoke(cmd, (args ?? {}) as never, options);
}
export default invoke;
