/**
 * Generated by `ztron codegen`. Do not edit by hand.
 * Run `ztron codegen` after adding/changing commands.
 */
import { invoke as rawInvoke } from "@zturnlibs/ztron-api";
import type { InvokeOptions } from "@zturnlibs/ztron-api";

export type KnownCommands = {
    "d2r:getConfig": { args: Record<string, never>; result: { config: { version: number; gameDir: string | null; sources: { id: string; path: string; label: string; addedAt: number }[]; knownMods: { key: string; name: string; displayName: string | null; savepath: string; sourceId: string; sourcePath: string; relPath: string; variant: string; parseWarning: string | null; readmePath: string | null; }[]; profiles: { id: string; name: string; modName: string; extraArgs: string[]; note: string; createdAt: number }[]; installed: Record<string, { mode: string; installedAt: number; sourcePath: string }>; autoBackup: boolean; backupKeep: number; backupZip: boolean; updateState: Record<string, { supported: boolean; localVersion: string | null; remoteVersion: string | null; hasUpdate: boolean; downloadUrl: string | null; configUrl: string | null; changelog: string | null; lastChecked: number; error: string | null; }>; }; validation: { exists: boolean; hasD2R: boolean; hasModsDir: boolean } | null; } }
    "d2r:setGameDir": { args: { gameDir: string }; result: { ok: boolean; validation: { exists: boolean; hasD2R: boolean; hasModsDir: boolean } } }
    "d2r:pickFolder": { args: { title?: string }; result: { path: string | null } }
    "d2r:addSource": { args: { path: string; label?: string }; result: { source: { id: string; path: string; label: string; addedAt: number }; } }
    "d2r:removeSource": { args: { id: string }; result: { ok: boolean } }
    "d2r:scanSource": { args: { id: string }; result: { mods: { key: string; name: string; displayName: string | null; savepath: string; sourceId: string; sourcePath: string; relPath: string; variant: string; parseWarning: string | null; readmePath: string | null; }[]; warnings: string[]; scannedDirs: number; } }
    "d2r:listMods": { args: Record<string, never>; result: { mods: { key: string; name: string; displayName: string | null; savepath: string; sourceId: string; sourcePath: string; relPath: string; variant: string; parseWarning: string | null; readmePath: string | null; }[]; installed: Record<string, boolean>; suggestedArgs: Record<string, string[]>; } }
    "d2r:installMod": { args: { key: string; mode: string; overwrite: boolean; ch: string }; result: { ok: boolean; files: number; bytes: number; mode: string; errors: string[] } }
    "d2r:uninstallPreflight": { args: { name: string }; result: { installed: boolean; savepath: string | null; usesRootSaves: boolean; saveDir: string | null; saveDirExists: boolean; } }
    "d2r:uninstallMod": { args: { name: string }; result: { ok: boolean } }
    "d2r:readTextB64": { args: { path: string }; result: { b64: string | null; size: number } }
    "d2r:saveProfiles": { args: { profiles: { id: string; name: string; modName: string; extraArgs: string[]; note: string; createdAt: number }[]; }; result: { profiles: { id: string; name: string; modName: string; extraArgs: string[]; note: string; createdAt: number }[]; } }
    "d2r:launch": { args: { modName: string; extraArgs: string[] }; result: { pid: number; args: string[] } }
    "d2r:exportShortcut": { args: { name: string; modName: string; extraArgs: string[] }; result: { lnkPath: string } }
    "d2r:openDir": { args: { path: string }; result: { ok: boolean } }
    "d2r:saveOverview": { args: Record<string, never>; result: { root: { name: string; slot: string; path: string; exists: boolean; files: { name: string; size: number; mtime: number }[]; dirs: { name: string; files: number; bytes: number }[]; totalBytes: number; }; mods: { name: string; slot: string; path: string; exists: boolean; files: { name: string; size: number; mtime: number }[]; dirs: { name: string; files: number; bytes: number }[]; totalBytes: number; }[]; } }
    "d2r:listBackups": { args: Record<string, never>; result: { dir: string; backups: { id: string; createdAt: number; note: string; trigger: string; scopes: { slot: string; sourcePath: string }[]; files: number; bytes: number; size: number; zip: boolean; signature: string; }[]; } }
    "d2r:backupNow": { args: { slots: string[]; note?: string }; result: { backup: { id: string; createdAt: number; note: string; trigger: string; scopes: { slot: string; sourcePath: string }[]; files: number; bytes: number; size: number; zip: boolean; signature: string; }; } }
    "d2r:restoreBackup": { args: { id: string }; result: { ok: boolean; preRestoreId: string | null } }
    "d2r:deleteBackup": { args: { id: string }; result: { ok: boolean } }
    "d2r:setBackupNote": { args: { id: string; note: string }; result: { ok: boolean } }
    "d2r:setSavePrefs": { args: { autoBackup?: boolean; backupKeep?: number; backupZip?: boolean }; result: { ok: boolean; autoBackup: boolean; backupKeep: number; backupZip: boolean } }
    "d2r:checkGameRunning": { args: Record<string, never>; result: { running: boolean } }
    "d2r:stashPickFile": { args: { title?: string }; result: { path: string | null } }
    "d2r:stashPreflight": { args: { slot: string }; result: { slot: string; fileName: string; path: string; exists: boolean; size: number; mtime: number; gameRunning: boolean; } }
    "d2r:stashReplace": { args: { slot: string; sourcePath: string; note?: string }; result: { ok: boolean; backupId: string | null; replaced: boolean } }
    "d2r:stashConsistency": { args: Record<string, never>; result: { soft: { slot: string; fileName: string; path: string; exists: boolean; size: number; mtime: number; header: { hardcore: boolean; version: number; sharedGold: number; sectorSize: number; pageCount: number | null; } | null; }; hard: { slot: string; fileName: string; path: string; exists: boolean; size: number; mtime: number; header: { hardcore: boolean; version: number; sharedGold: number; sectorSize: number; pageCount: number | null; } | null; }; warnings: { level: string; text: string }[]; } }
    "d2r:stashHeader": { args: { path: string }; result: { hardcore: boolean; version: number; sharedGold: number; sectorSize: number; pageCount: number | null; } | null }
    "d2r:modScripts": { args: Record<string, never>; result: { mods: { mod: string; scripts: { name: string; path: string; size: number; mtime: number; sideEffects: { killsGame: boolean; launchesGame: boolean; pauses: boolean }; missingTargets: string[]; truncated: boolean; b64: string; }[]; }[]; } }
    "d2r:runScript": { args: { modName: string; fileName: string; ch: string }; result: { ok: boolean; code: number | null; timedOut: boolean } }
    "d2r:listCharacters": { args: { slot: string }; result: { slot: string; path: string; exists: boolean; characters: { name: string; d2sName: string; size: number; mtime: number; companions: { name: string; size: number }[]; }[]; } }
    "d2r:transferCharacters": { args: { fromSlot: string; toSlot: string; names: string[]; mode: string; }; result: { ok: boolean; backupId: string | null; characters: number; files: number; mode: string; } }
    "d2r:filterList": { args: Record<string, never>; result: { presets: { file: string; name: string; ruleCount: number; enabledCount: number; mtime: number; size: number }[]; root: string; rootExists: boolean; } }
    "d2r:filterRead": { args: { file: string }; result: { name: string; rules: { name?: unknown; enabled?: unknown; ruleType?: unknown; [key: string]: unknown }[]; summaries: string[]; warning: string | null; } }
    "d2r:filterUpdate": { args: { file: string; changes: { index: number; enabled: boolean }[] }; result: { backedUp: string | null; changed: number; gameRunning: boolean } }
    "d2r:filterBackups": { args: { file: string }; result: { backups: { name: string; mtime: number; size: number }[] } }
    "d2r:filterRestoreBackup": { args: { file: string; backup: string }; result: { ok: boolean; backedUp: string | null } }
    "d2r:filterDeleteBackup": { args: { file: string; backup: string }; result: { ok: boolean } }
    "d2r:filterImport": { args: Record<string, never>; result: { file: string | null } }
    "d2r:filterExport": { args: { file: string }; result: { path: string | null } }
    "d2r:filterDuplicate": { args: { file: string; newName: string }; result: { file: string } }
    "d2r:filterRename": { args: { file: string; newName: string }; result: { file: string } }
    "d2r:filterDelete": { args: { file: string }; result: { ok: boolean; backedUp: string | null } }
    "d2r:itemSources": { args: Record<string, never>; result: { groups: { name: string; slot: string; path: string; exists: boolean; stashes: { name: string; path: string; size: number; mtime: number; kind: string }[]; characters: { name: string; path: string; size: number; mtime: number }[]; }[]; } }
    "d2r:itemView": { args: { path: string }; result: | { kind: "stash"; version: string; hardcore: boolean; sharedGold: number; pageCount: number; pages: { index: number; name: string; items: { type: string; name: string; quality: string; category: string; where: string; page: number; x: number; y: number; qty: number | null; level: number | null; ethereal: boolean; socketed: boolean; sockets: number | null; identified: boolean; }[]; }[]; } | { kind: "character"; name: string; className: string | null; level: number | null; hardcore: boolean; expansion: boolean; groups: { where: string; items: { type: string; name: string; quality: string; category: string; where: string; page: number; x: number; y: number; qty: number | null; level: number | null; ethereal: boolean; socketed: boolean; sockets: number | null; identified: boolean; }[]; }[]; } | { /** 物品明细解不出（mod 自定义 SaveBits 位宽），头部身份已提取 */ kind: "character-partial"; name: string; className: string | null; level: number | null; hardcore: boolean; expansion: boolean; message: string; } | { kind: "error"; message: string } }
    "d2r:postExitCheck": { args: Record<string, never>; result: { running: boolean; watched: boolean; changed: boolean; lost: string[]; backupId: string | null; preLaunchBackupId: string | null; } }
    "d2r:healthCheck": { args: Record<string, never>; result: { gameDir: string | null; durationMs: number; items: { id: string; group: "path" | "lang" | "version" | "av" | "saves" | "system"; title: string; status: "ok" | "info" | "warn" | "fail"; detail: string; fixSummary: string | null; fixSteps: string[]; }[]; } }
    "d2r:updateCheck": { args: { name?: string; force?: boolean }; result: { results: Record<string, { supported: boolean; localVersion: string | null; remoteVersion: string | null; hasUpdate: boolean; downloadUrl: string | null; configUrl: string | null; changelog: string | null; lastChecked: number; error: string | null; }>; } }
    "d2r:updateApply": { args: { name: string; mode: string; overwrite: boolean; ch: string }; result: { ok: boolean; files: number; bytes: number; mode: string; errors: string[] } }
    "d2r:modIndexList": { args: { refresh?: boolean }; result: { entries: { id: string; name: string; author: string; category: string; version: string; language?: string; homepage: string | null; downloadUrl: string | null; configUrl: string | null; description: string; notes?: string; }[]; fetchedAt: number; via: string; bundledFallback: boolean; errorsText: string | null; } }
    "d2r:zipStagePick": { args: Record<string, never>; result: { stage: { stageId: string; candidates: { name: string; displayName: string | null; savepath: string; variant: string; sourcePath: string; }[]; files: number; bytes: number; } | null; } }
    "d2r:zipStageUrl": { args: { url: string; ch: string }; result: { stage: { stageId: string; candidates: { name: string; displayName: string | null; savepath: string; variant: string; sourcePath: string; }[]; files: number; bytes: number; } | null; } }
    "d2r:zipStageInstall": { args: { stageId: string; modName: string; mode: string; overwrite: boolean; source?: string; ch: string }; result: { ok: boolean; files: number; bytes: number; mode: string; errors: string[] } }
};

/** Type-safe invoke: cmd must be a known command, args/result inferred from its declaration. */
export function invoke<C extends keyof KnownCommands>(
  cmd: C,
  args: KnownCommands[C]["args"],
  options?: InvokeOptions,
): Promise<KnownCommands[C]["result"]>;

export async function invoke(
  cmd: string,
  args?: unknown,
  options?: InvokeOptions,
): Promise<unknown> {
  if (cmd === "d2r:getConfig") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:setGameDir") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:pickFolder") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:addSource") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:removeSource") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:scanSource") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:listMods") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:installMod") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:uninstallPreflight") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:uninstallMod") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:readTextB64") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:saveProfiles") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:launch") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:exportShortcut") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:openDir") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:saveOverview") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:listBackups") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:backupNow") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:restoreBackup") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:deleteBackup") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:setBackupNote") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:setSavePrefs") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:checkGameRunning") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:stashPickFile") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:stashPreflight") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:stashReplace") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:stashConsistency") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:stashHeader") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:modScripts") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:runScript") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:listCharacters") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:transferCharacters") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:filterList") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:filterRead") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:filterUpdate") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:filterBackups") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:filterRestoreBackup") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:filterDeleteBackup") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:filterImport") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:filterExport") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:filterDuplicate") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:filterRename") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:filterDelete") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:itemSources") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:itemView") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:postExitCheck") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:healthCheck") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:updateCheck") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:updateApply") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:modIndexList") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:zipStagePick") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:zipStageUrl") return rawInvoke(cmd, args as never, options);
  if (cmd === "d2r:zipStageInstall") return rawInvoke(cmd, args as never, options);
  return rawInvoke(cmd, (args ?? {}) as never, options);
}
export default invoke;
